#!/bin/bash
cat << EOT >> ~/.bashrc
source /opt/ros/kinetic/setup.bash
export ROS_MASTER_URI=http://$(/sbin/ip -o -4 addr list eth0 | awk '{if(NR==1)print $4}' | cut -d/ -f1):11311
export ROS_IP=$(/sbin/ip -o -4 addr list eth0 | awk '{if(NR==1)print $4}' | cut -d/ -f1)
EOT
echo "Almost there...."
sudo apt install -y ros-kinetic-rosapi ros-kinetic-rosauth libbson-dev python-bson iputils-ping >/dev/null 2>&1
echo "done!"
